{
  System.out.println("continuationUnwindTest enter");
  try {
    expect(callWithCurrentContinuation(new CallbackReceiver<Integer>(){
      public Integer receive(      final Callback<Integer> continuation) throws Exception {
        unwindTest(new Callable<Integer>(){
          public Integer call() throws Exception {
            return receiver.receive(continuation);
          }
        }
);
        throw new AssertionError();
      }
    }
) == 42);
  }
 catch (  MyException e) {
    e.printStackTrace();
  }
  System.out.println("continuationUnwindTest expect");
  expect(before == 1);
  expect(task == 1);
  expect(after == 1);
  System.out.println("continuationUnwindTest exit");
}
